---
- name: Install Docker, configure user, and download WordPress theme
  hosts: all
  become: true
  gather_facts: yes

  # Include tasks and variables from separate files
  vars_files:
    - vars.yml

  tasks:
    - include_tasks: tasks/docker_install.yml
    - include_tasks: tasks/wp_setup.yml